on:
  workflow_dispatch:
  schedule:
  - cron: "0 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.4
    steps:
      - name: install deps
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        shell: Rscript {0}
        run: |
          install.packages(c('oce', 'fable'))
          
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SAWATER_API_USERNAME: ${{ secrets.SAWATER_API_USERNAME }}
          SAWATER_API_PASSWORD: ${{ secrets.SAWATER_API_PASSWORD }}
        run:  | 
          /usr/local/bin/r $GITHUB_WORKSPACE/workflows/default/combined_workflow.R
